### ISSUE TITLE
Multi receiver support not functional

### ISSUE THREAD

**Issue by nimeshaperi** [team-watchdog/Apocalypes-mobile-app#25]
The application doesn't allow switching between different receivers. Couldn't connect to another receiver while a receiver is registered.

**Comment by yudhanjaya** [comment]
I think it’s fine to keep this as a safety feature, to prevent people
accidentally adding other people’s receivers. Maybe we give them the option
to register and de register a single receiver.

**Comment by nimeshaperi** [comment]
Not supporting multiple receivers at this point.
